### ISSUE TITLE
Move from internal testing track to alpha (closed)

### ISSUE THREAD

**Issue by MitchellQ** [ssm-deepcove/discover_deep_cove#120]
I would like us to resolve all the issues marked as "Prior: On-Site Testing" .

This needs to be done for several reasons

- When these are resolved then I believe we are ready to switch tracks (proper testing with peers and target audience
- Make sure that there is not the same lengthy review process that we encountered when first uploading to internal testing

I believe this should happen by end of Sepetember - mid October at the latest.

The issues we need to resolve are
- [ ] Issue #66 - deny permissions
- [ ] Issue #46 - markers remain locked
- [x] Issue #10 - lenovo qr scan

**Comment by MitchellQ** [comment]
We have changed tracks without issue #66 and #46
