### ISSUE TITLE
Notice board: clear old notices

### ISSUE THREAD

**Issue by samuelgrant** [ssm-deepcove/discover_deep_cove#152]
The notice board needs (#27)  to clear messages that are no longer active. Are we using the `DeletedAt` or `Active` database fields?

As a subsequent feature, do we wish to allow the users to swipe away notifications of the notice board that are not urgent? @ssm-deepcove/developers 

**Tasks**:
- [ ] Confirm what field we are using on the database to determine active/inactive
- [ ] If we are using `DeletedAt` then make a migration and PR on [the website repo](https://github.com/ssm-deepcove/deepcove-website) that removes the `Active` field
- [ ] Confirm that the phone app clears old notices as required.

**Comment by jacksos101** [comment]
We are using both.

Only active notices will be pushed to the app (or website). When the notices are refreshed in the app, stale ones will be deleted.

Notices that are inactive, but not deleted, remain in the noticeboard management (this means that notices that apply regularly don't have to be rewritten each time). When an inactive notice is made active, the updated at field will be set to current time. 

Deleted notices do not show anywhere.

I wasn't going to implement dismissable notices, don't feel that its really needed.

**Comment by samuelgrant** [comment]
Ok sounds good.
